version: '3.8'

services:
 n8n:
   image: n8nio/n8n
   restart: always
   ports:
     - "5678:5678"
   volumes:
     - n8n_data:/home/node/.n8n
   environment:
     - DB_TYPE=postgresdb
     - DB_POSTGRESDB_HOST=postgres
     - DB_POSTGRESDB_PORT=5432
     - DB_POSTGRESDB_DATABASE=n8n
     - DB_POSTGRESDB_USER=n8n
     - DB_POSTGRESDB_PASSWORD=n8n_password
     - N8N_BASIC_AUTH_ACTIVE=true
     - N8N_BASIC_AUTH_USER=user
     - N8N_BASIC_AUTH_PASSWORD=password
   depends_on:
     - postgres

 postgres:
   image: postgres:15
   restart: always
   environment:
     - POSTGRES_DB=n8n
     - POSTGRES_USER=n8n
     - POSTGRES_PASSWORD=n8n_password
   volumes:
     - pg_data:/var/lib/postgresql/data

volumes:
 n8n_data:
 pg_data: 